### ISSUE TITLE
[Task] server - Riot API understanding -5.17

### ISSUE THREAD

**Issue by leehojun0314** [codestates/Lollin-server#4]
### ISSUE
* Group : server
* Type :  research
* Detail: fix actions from client/server

### TODO
- [x]  Get list of item datas
- [x] Get list of champion datas
- [x]  Get active game information ★☆★☆★☆

### Estimated time
6h

### Labels
* Estimated time : E: 6h
* Group : server
* Sprint : Sprint__NUMBER__
* Urgency : High
